const express = require('express')
const path = require('path')
const app = express()
app.use(express.static(path.join(__dirname, 'dist')))
app.listen(8080, '0.0.0.0', () => console.log('Serving dist/ at http://localhost:8080'))
